leftnav:
- identifier: ca084ba8-afe6-7030-3bc7-3ff8311dfc12
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 9e3f3072-4c55-0b19-7f1f-9a984910bd5f
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: a96a72a7-2b02-6c71-2d3f-e80f44c1b0cb
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 504bb3da-f1cf-ff67-579f-c3c6a037a720
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 57b17c47-0331-a639-8000-b6bd03eb98be
  name: Exams
  pageRef: /pages/exams
  weight: 50
